#!/usr/bin/env python3
"""
Convert .config (key=value) to a C header.

Usage:
    python3 tools/config_to_header.py <.config> <output.h>
    python3 tools/config_to_header.py <.config> <output.h> --keep-prefix
    python3 tools/config_to_header.py <.config> <output.h> --prefix MYCFG_

By default, strips the CONFIG_ prefix (CONFIG_FOO=y -> #define FOO 1).
Use --keep-prefix to preserve it, or --prefix to strip a custom prefix.
"""
import re
import sys
import os
import argparse


def convert(dotconfig_path: str, header_path: str,
            keep_prefix: bool = False, prefix: str = "CONFIG_"):
    if not os.path.exists(dotconfig_path):
        print(f"Error: {dotconfig_path} not found.")
        sys.exit(1)

    lines = []
    with open(dotconfig_path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()

            # format: # CONFIG_XXX is not set
            if line.startswith("#") and "is not set" in line:
                m = re.match(r"#\s*(\w+)\s+is not set", line)
                if m:
                    name = m.group(1)
                    if not keep_prefix and name.startswith(prefix):
                        name = name[len(prefix):]
                    lines.append(f"/* #undef {name} */")
                continue

            # format: CONFIG_XXX=value
            m = re.match(r"(\w+)=(.+)", line)
            if not m:
                continue
            name, val = m.group(1), m.group(2)
            val = val.strip('"')

            if not keep_prefix and name.startswith(prefix):
                name = name[len(prefix):]

            if val == "y":
                lines.append(f"#define {name} 1")
            elif val == "n":
                lines.append(f"/* #undef {name} */")
            else:
                lines.append(f"#define {name} {val}")

    os.makedirs(os.path.dirname(header_path) or ".", exist_ok=True)

    guard = "_" + os.path.basename(header_path).upper().replace(".", "_").replace("-", "_") + "_"
    content = (
        f"/* Auto-generated by config_to_header.py, DO NOT EDIT */\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
    )
    for ln in lines:
        content += ln + "\n"
    content += f"\n#endif /* {guard} */\n"

    if os.path.exists(header_path):
        with open(header_path, "r", encoding="utf-8") as f:
            if f.read() == content:
                print(f"Up-to-date {header_path}")
                return

    with open(header_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated {header_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert .config to a C header")
    parser.add_argument("dotconfig", help="Path to .config file")
    parser.add_argument("header", help="Path to output header file")
    parser.add_argument("--keep-prefix", action="store_true",
                        help="Preserve the CONFIG_ prefix in macro names")
    parser.add_argument("--prefix", default="CONFIG_",
                        help="Prefix to strip (default: CONFIG_)")
    args = parser.parse_args()

    if args.keep_prefix and args.prefix != "CONFIG_":
        parser.error("--keep-prefix and --prefix are mutually exclusive")

    convert(args.dotconfig, args.header,
            keep_prefix=args.keep_prefix, prefix=args.prefix)
